### ISSUE TITLE
Data block "ibm_database_connection" does not take "public-and-private" as endpoint type

### ISSUE THREAD

**Issue by Ak-sky** [terraform-ibm-modules/terraform-ibm-icd-mysql#48]
This data block https://github.com/terraform-ibm-modules/terraform-ibm-icd-mysql/blob/8722c020090f559db956545714321f31701ff211/main.tf#L220

only take values `public` and `private` as [endpoint type](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/database_connection#endpoint_type), which is creating an issue when passing `public-and-private` by direclty passing this variable value as `public-and-private` as it is an allowed value in variable constraints. https://github.com/terraform-ibm-modules/terraform-ibm-icd-mysql/blob/8722c020090f559db956545714321f31701ff211/variables.tf#L79

Should we have some conditional check on the data block `endpoint_type` based on the `service_endpoints` as it supports`public`, `private` and `public-and-private`  or should we create another variable for `endpoint_type`?

**Comment by ocofaigh** [comment]
@Ak-sky I suggest use logic like this instead:

```
data "ibm_database_connection" "database_connection" {
  endpoint_type = var.service_endpoints == "public-and-private" ? "public" : "private"
  deployment_id = ibm_database.mysql_db.id
  user_id       = ibm_database.mysql_db.adminuser
  user_type     = "database"
}
```

**Comment by Ak-sky** [comment]
Release available in https://github.com/terraform-ibm-modules/terraform-ibm-icd-mysql/releases/tag/v1.2.4, closing this.
